spring:
  application:
    name: java-advanced
  datasource:
    url: jdbc:h2:mem:${spring.application.name}-db
    username: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

