spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:${spring.application.name}-db
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

service:
  aluno:
    concat-id-to-aluno: enabled
